name: "Sample workflow to call a workflow in another repository"

on:
  push:
  workflow_dispatch:
  
jobs:
  greet_user:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to Tom
        uses: rodmhgl/reusable/.github/workflows/reusable-workflow.yml@main
        with:
          username: Tom